name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint (if available)
        run: |
          if [ -f package.json ] && grep -q '"lint"' package.json; then npm run lint; else echo "No lint script"; fi
      - name: Type check (if available)
        run: |
          if [ -f package.json ] && grep -q '"type-check"' package.json; then npm run type-check; else echo "No type-check script"; fi
      - name: Build (if available)
        run: |
          if [ -f package.json ] && grep -q '"build"' package.json; then npm run build; else echo "No build script"; fi 